export const categories = [
  { name: "Fast Food", image: "/placeholder.svg?height=120&width=120" },
  { name: "Breakfast", image: "/placeholder.svg?height=120&width=120" },
  { name: "Burgers", image: "/placeholder.svg?height=120&width=120" },
  { name: "Coffee", image: "/placeholder.svg?height=120&width=120" },
  { name: "Sushi", image: "/placeholder.svg?height=120&width=120" },
  { name: "Healthy", image: "/placeholder.svg?height=120&width=120" },
  { name: "Chicken", image: "/placeholder.svg?height=120&width=120" },
  { name: "Comfort Food", image: "/placeholder.svg?height=120&width=120" },
  { name: "Desserts", image: "/placeholder.svg?height=120&width=120" },
  { name: "Asian", image: "/placeholder.svg?height=120&width=120" },
  { name: "Bubble Tea", image: "/placeholder.svg?height=120&width=120" },
  { name: "Pizza", image: "/placeholder.svg?height=120&width=120" },
  { name: "Smoothie", image: "/placeholder.svg?height=120&width=120" },
  { name: "Bakery", image: "/placeholder.svg?height=120&width=120" },
]