/**
 * Mock merchant data for each store
 * This data structure represents all merchant-related data per store
 */

export interface StoreMerchantData {
  storeId: string
  storeName: string

  // Modifiers
  modifiers: {
    modifiers: Modifier[]
  }
  
  // Home/Analytics
  home: {
    metrics: {
      totalSales: number
      totalOrders: number
      totalCustomers: number
      averageOrderValue: number
    }
    lastUpdated: number
    selectedDateRange: string
  }
  
  // Orders
  orders: {
    orders: Array<{
      customer: string
      orderId: string
      orderStatus: "Completed" | "Cancelled - Not Paid" | "Active" | "Scheduled"
      date: string
      time: string
      fulfillmentStatus: string
      fulfillmentType: "Customer pickup" | "DoorDash delivery"
      channel: string
      subtotal: string
    }>
    searchQuery: string
    selectedFilter: string
    activeTab: "Active" | "Scheduled" | "History"
  }
  
  // Menu
  menu: {
    categories: Array<{
      id: string
      name: string
      items: Array<{
        id: string
        name: string
        image: string
        pickupPrice: string
        deliveryPrice: string
        status: string
      }>
    }>
    expandedCategories: string[]
    showBanner: boolean
  }
  
  // Users
  users: {
    users: Array<{
      id: string
      role: string
      email: string
      firstName: string
      lastName: string
    }>
  }
  
  // Settings
  settings: {
    store: {
      storeName: string
      address: string
      phoneNumber: string
      website: string
      description: string
    }
    account: {
      autoGeneratedDescriptions: boolean
      alcoholSales: boolean
      useCustomerPhotos: boolean
      tabletAccess: boolean
      tabletPin: string
      chatFeature: boolean
      staffTips: boolean
    }
  }
  
  // Store Availability
  storeAvailability: {
    storeStatus: "Active" | "Paused" | "Deactivated"
    pauseUntil?: string
    menuHours: Array<{
      day: string
      slots: Array<{ start: string; end: string }>
      closed: boolean
    }>
    selectedMenu: string
  }
}

export type ModifierStatus =
  | 'In stock'
  | 'Out of stock'
  | 'Out of stock - 4 hours'
  | 'Out of stock - Today'
  | 'Out of stock - 1 week'
  | 'Out of stock - Custom'
  | 'Out of stock - Indefinitely'

export interface Modifier {
  id: string
  name: string
  options: string[]
  usedIn: Array<{ id: string; name: string }>
  status: ModifierStatus
  timing?: string
  required?: boolean
  allowMultipleOptions?: boolean
  allowMultipleSameOption?: boolean
  allowFreeOptions?: boolean
}

export const merchantStoreData: Record<string, StoreMerchantData> = {
  "philz-coffee": {
    storeId: "philz-coffee",
    storeName: "Frosty Bear test NCP 🐻🍯",
    home: {
      metrics: {
        totalSales: 12500.50,
        totalOrders: 342,
        totalCustomers: 198,
        averageOrderValue: 36.55
      },
      lastUpdated: Date.now(),
      selectedDateRange: "Last 7 days"
    },
    orders: {
      orders: [
        {
          customer: "John Doe",
          orderId: "DD-123456",
          orderStatus: "Completed",
          date: "4/28/2025",
          time: "2:30 PM",
          fulfillmentStatus: "Delivered",
          fulfillmentType: "DoorDash delivery",
          channel: "DoorDash",
          subtotal: "$25.50"
        },
        {
          customer: "Jane Smith",
          orderId: "DD-123457",
          orderStatus: "Cancelled - Not Paid",
          date: "4/27/2025",
          time: "1:15 PM",
          fulfillmentStatus: "Cancelled",
          fulfillmentType: "DoorDash delivery",
          channel: "DoorDash",
          subtotal: "$18.75"
        }
      ],
      searchQuery: "",
      selectedFilter: "All channels",
      activeTab: "History"
    },
    menu: {
      categories: [
        {
          id: "coffee",
          name: "Coffee",
          items: [
            {
              id: "1",
              name: "Mint Mojito Iced Coffee",
              image: "/placeholder.jpg",
              pickupPrice: "$6.50",
              deliveryPrice: "$7.00",
              status: "In stock"
            },
            {
              id: "2",
              name: "Tesora",
              image: "/placeholder.jpg",
              pickupPrice: "$5.50",
              deliveryPrice: "$6.00",
              status: "In stock"
            }
          ]
        }
      ],
      expandedCategories: ["coffee"],
      showBanner: true
    },
    modifiers: {
      modifiers: [
        {
          id: "milk-choice",
          name: "Milk Choice",
          options: ["Whole", "Skim", "Oat"],
          usedIn: [
            { id: "1", name: "Mint Mojito Iced Coffee" },
            { id: "2", name: "Tesora" }
          ],
          status: "In stock",
          timing: "All Day",
          required: false,
          allowMultipleOptions: false,
          allowMultipleSameOption: false,
          allowFreeOptions: false
        },
        {
          id: "sweetener",
          name: "Sweetener",
          options: ["Classic", "Less Sweet", "Sugar-Free"],
          usedIn: [{ id: "1", name: "Mint Mojito Iced Coffee" }],
          status: "In stock",
          timing: "All Day",
          required: false,
          allowMultipleOptions: false,
          allowMultipleSameOption: false,
          allowFreeOptions: false
        },
        {
          id: "temp-preference",
          name: "Temperature",
          options: ["Hot", "Iced"],
          usedIn: [
            { id: "1", name: "Mint Mojito Iced Coffee" },
            { id: "2", name: "Tesora" }
          ],
          status: "In stock",
          timing: "All Day",
          required: false,
          allowMultipleOptions: false,
          allowMultipleSameOption: false,
          allowFreeOptions: false
        }
      ]
    },
    users: {
      users: [
        {
          id: "1",
          role: "Business Admin",
          email: "kkapoor@bombaycafe.com",
          firstName: "Kira",
          lastName: "Kapoor"
        }
      ]
    },
    settings: {
      store: {
        storeName: "Frosty Bear test NCP 🐻🍯",
        address: "575 Bellevue Sq, Bellevue, WA 98004, USA",
        phoneNumber: "",
        website: "http://himalayan-grill.com",
        description: "Hand crafted burgers, made the way they were intended to be."
      },
      account: {
        autoGeneratedDescriptions: true,
        alcoholSales: false,
        useCustomerPhotos: false,
        tabletAccess: true,
        tabletPin: "1 2 3 6",
        chatFeature: true,
        staffTips: false
      }
    },
    storeAvailability: {
      storeStatus: "Paused",
      pauseUntil: "12:16 AM PDT on 4/29/2025",
      menuHours: [
        { day: "Monday", slots: [{ start: "07:00 AM", end: "09:00 PM" }], closed: false },
        { day: "Tuesday", slots: [{ start: "07:00 AM", end: "09:00 PM" }], closed: false },
        { day: "Wednesday", slots: [{ start: "07:00 AM", end: "09:00 PM" }], closed: false },
        { day: "Thursday", slots: [{ start: "07:00 AM", end: "09:00 PM" }], closed: false },
        { day: "Friday", slots: [{ start: "07:00 AM", end: "09:00 PM" }], closed: false },
        { day: "Saturday", slots: [{ start: "07:00 AM", end: "09:00 PM" }], closed: false },
        { day: "Sunday", slots: [{ start: "07:00 AM", end: "09:00 PM" }], closed: false }
      ],
      selectedMenu: "Grid Iron Waffle | TEST TEST TEST SSME"
    }
  },
  "bombay-cafe": {
    storeId: "bombay-cafe",
    storeName: "Bombay Cafe",
    home: {
      metrics: {
        totalSales: 23400.75,
        totalOrders: 567,
        totalCustomers: 312,
        averageOrderValue: 41.27
      },
      lastUpdated: Date.now(),
      selectedDateRange: "Last 7 days"
    },
    orders: {
      orders: [
        {
          customer: "Sarah Johnson",
          orderId: "DD-789012",
          orderStatus: "Completed",
          date: "4/28/2025",
          time: "3:45 PM",
          fulfillmentStatus: "Delivered",
          fulfillmentType: "DoorDash delivery",
          channel: "DoorDash",
          subtotal: "$42.30"
        }
      ],
      searchQuery: "",
      selectedFilter: "All channels",
      activeTab: "History"
    },
    menu: {
      categories: [
        {
          id: "curries",
          name: "Curries",
          items: [
            {
              id: "1",
              name: "Butter Chicken",
              image: "/placeholder.jpg",
              pickupPrice: "$18.99",
              deliveryPrice: "$20.99",
              status: "In stock"
            },
            {
              id: "2",
              name: "Chicken Tikka Masala",
              image: "/placeholder.jpg",
              pickupPrice: "$17.99",
              deliveryPrice: "$19.99",
              status: "In stock"
            }
          ]
        }
      ],
      expandedCategories: ["curries"],
      showBanner: false
    },
    modifiers: {
      modifiers: [
        {
          id: "spice-level",
          name: "Spice Level",
          options: ["Mild", "Medium", "Hot"],
          usedIn: [
            { id: "1", name: "Butter Chicken" },
            { id: "2", name: "Chicken Tikka Masala" }
          ],
          status: "In stock",
          timing: "All Day",
          required: false,
          allowMultipleOptions: false,
          allowMultipleSameOption: false,
          allowFreeOptions: false
        },
        {
          id: "protein-choice",
          name: "Choose Protein",
          options: ["Paneer", "Chicken", "Lamb"],
          usedIn: [
            { id: "1", name: "Butter Chicken" },
            { id: "2", name: "Chicken Tikka Masala" }
          ],
          status: "In stock",
          timing: "All Day",
          required: false,
          allowMultipleOptions: false,
          allowMultipleSameOption: false,
          allowFreeOptions: false
        }
      ]
    },
    users: {
      users: [
        {
          id: "1",
          role: "Manager",
          email: "manager@bombaycafe.com",
          firstName: "Raj",
          lastName: "Patel"
        }
      ]
    },
    settings: {
      store: {
        storeName: "Bombay Cafe",
        address: "123 Main St, Seattle, WA 98101, USA",
        phoneNumber: "(206) 555-0123",
        website: "http://bombaycafe.com",
        description: "Authentic Indian cuisine with traditional flavors and modern presentation."
      },
      account: {
        autoGeneratedDescriptions: false,
        alcoholSales: true,
        useCustomerPhotos: true,
        tabletAccess: true,
        tabletPin: "2 4 6 8",
        chatFeature: false,
        staffTips: true
      }
    },
    storeAvailability: {
      storeStatus: "Active",
      menuHours: [
        { day: "Monday", slots: [{ start: "11:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Tuesday", slots: [{ start: "11:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Wednesday", slots: [{ start: "11:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Thursday", slots: [{ start: "11:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Friday", slots: [{ start: "11:00 AM", end: "11:00 PM" }], closed: false },
        { day: "Saturday", slots: [{ start: "11:00 AM", end: "11:00 PM" }], closed: false },
        { day: "Sunday", slots: [{ start: "12:00 PM", end: "09:00 PM" }], closed: false }
      ],
      selectedMenu: "Main Menu"
    }
  },
  "walgreens": {
    storeId: "walgreens",
    storeName: "Walgreens",
    home: {
      metrics: {
        totalSales: 8900.25,
        totalOrders: 234,
        totalCustomers: 156,
        averageOrderValue: 38.03
      },
      lastUpdated: Date.now(),
      selectedDateRange: "Last 7 days"
    },
    orders: {
      orders: [
        {
          customer: "Mike Wilson",
          orderId: "DD-345678",
          orderStatus: "Completed",
          date: "4/28/2025",
          time: "10:30 AM",
          fulfillmentStatus: "Delivered",
          fulfillmentType: "DoorDash delivery",
          channel: "DoorDash",
          subtotal: "$15.99"
        }
      ],
      searchQuery: "",
      selectedFilter: "All channels",
      activeTab: "History"
    },
    menu: {
      categories: [
        {
          id: "pharmacy",
          name: "Pharmacy Items",
          items: [
            {
              id: "1",
              name: "Prescription Pickup",
              image: "/placeholder.jpg",
              pickupPrice: "$0.00",
              deliveryPrice: "$5.99",
              status: "In stock"
            }
          ]
        }
      ],
      expandedCategories: ["pharmacy"],
      showBanner: false
    },
    modifiers: {
      modifiers: [
        {
          id: "gift-wrap",
          name: "Add Gift Wrap",
          options: ["Standard Wrap", "Premium Wrap"],
          usedIn: [{ id: "1", name: "Prescription Pickup" }],
          status: "In stock",
          timing: "All Day",
          required: false,
          allowMultipleOptions: false,
          allowMultipleSameOption: false,
          allowFreeOptions: false
        },
        {
          id: "delivery-speed",
          name: "Delivery Speed",
          options: ["Standard", "Express"],
          usedIn: [{ id: "1", name: "Prescription Pickup" }],
          status: "In stock",
          timing: "All Day",
          required: false,
          allowMultipleOptions: false,
          allowMultipleSameOption: false,
          allowFreeOptions: false
        }
      ]
    },
    users: {
      users: [
        {
          id: "1",
          role: "Store Manager",
          email: "manager@walgreens.com",
          firstName: "Lisa",
          lastName: "Anderson"
        }
      ]
    },
    settings: {
      store: {
        storeName: "Walgreens",
        address: "678 Tremont Street, Boston, MA 02118, USA",
        phoneNumber: "(617) 555-0198",
        website: "http://walgreens.com",
        description: "Your neighborhood pharmacy and convenience store."
      },
      account: {
        autoGeneratedDescriptions: true,
        alcoholSales: false,
        useCustomerPhotos: false,
        tabletAccess: true,
        tabletPin: "9 8 7 6",
        chatFeature: true,
        staffTips: false
      }
    },
    storeAvailability: {
      storeStatus: "Active",
      menuHours: [
        { day: "Monday", slots: [{ start: "08:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Tuesday", slots: [{ start: "08:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Wednesday", slots: [{ start: "08:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Thursday", slots: [{ start: "08:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Friday", slots: [{ start: "08:00 AM", end: "10:00 PM" }], closed: false },
        { day: "Saturday", slots: [{ start: "09:00 AM", end: "09:00 PM" }], closed: false },
        { day: "Sunday", slots: [{ start: "10:00 AM", end: "08:00 PM" }], closed: false }
      ],
      selectedMenu: "Store Catalog"
    }
  }
}

