export const restaurants = [
    {
        name: "7-Eleven",
        rating: 4.3,
        reviews: "(200+)",
        distance: "1.7 mi",
        time: "42 min",
        delivery: "A$0 delivery fee",
        sponsored: true,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "McDonald's",
        rating: 3.8,
        reviews: "(200+)",
        distance: "0.4 mi",
        time: "34 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Hungry Jacks",
        rating: 4.0,
        reviews: "(200+)",
        distance: "3.8 mi",
        time: "54 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "KFC",
        rating: 4.1,
        reviews: "(180+)",
        distance: "2.2 mi",
        time: "38 min",
        delivery: "A$0 delivery fee",
        sponsored: true,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Subway",
        rating: 4.0,
        reviews: "(150+)",
        distance: "1.3 mi",
        time: "29 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Domino's Pizza",
        rating: 3.9,
        reviews: "(170+)",
        distance: "2.0 mi",
        time: "40 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Nando's",
        rating: 4.4,
        reviews: "(220+)",
        distance: "2.7 mi",
        time: "45 min",
        delivery: "A$0 delivery fee",
        sponsored: true,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Oporto",
        rating: 4.2,
        reviews: "(190+)",
        distance: "1.9 mi",
        time: "36 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Red Rooster",
        rating: 3.7,
        reviews: "(140+)",
        distance: "3.2 mi",
        time: "50 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Boost Juice",
        rating: 4.5,
        reviews: "(160+)",
        distance: "0.8 mi",
        time: "25 min",
        delivery: "A$0 delivery fee",
        sponsored: true,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Sushi Hub",
        rating: 4.6,
        reviews: "(210+)",
        distance: "1.5 mi",
        time: "32 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
    {
        name: "Grill'd",
        rating: 4.3,
        reviews: "(250+)",
        distance: "2.4 mi",
        time: "37 min",
        delivery: "A$0 delivery fee",
        sponsored: false,
        image: "/placeholder.svg?height=200&width=200",
    },
]
