export const topCities = [
  'New York',
  'Houston',
  'San Francisco',
  'Vancouver, BC',
  'Los Angeles',
  'Brooklyn',
  'Seattle',
  'Miami',
  'Toronto',
  'San Diego',
  'Atlanta',
  'San Antonio',
  'Chicago',
  'Las Vegas',
  'Queens',
  'Bend',
  'Salt Lake City',
  'Birmingham',
  'Victoria',
  'Christchurch',
  'Huntsville',
  'Kamloops',
  'Jacksonville',
  'New Orleans',
  'Columbia',
  'Milwaukee',
  'Des Moines',
  'Tulsa',
  'Colorado Springs',
  'Lexington',
  'Scottsdale',
  'Pittsburgh',
  'Quebec City',
  'Tallahassee',
  'Austin',
  'Wilmington',
  'Orlando',
  'Augusta',
  'Ft. Worth',
  'All Cities',
];

