import { User } from '@/types/user-types';

// Initial user data extracted from review-data.ts
export const initialUsersData: User[] = [
  {
    id: 'user-2',
    name: 'Sarah Wilson',
    email: 'sarah.wilson@example.com',
    avatar: null,
    reviews: ['review-philz-2', 'review-sarah-2', 'review-sarah-3'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-3',
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    avatar: null,
    reviews: ['review-philz-3'],
    is_deleted: false,
    is_restricted: true,
  },
  {
    id: 'user-4',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@example.com',
    avatar: null,
    reviews: ['review-philz-4'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-5',
    name: 'David Brown',
    email: 'david.brown@example.com',
    avatar: null,
    reviews: ['review-mcd-1'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-6',
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    avatar: null,
    reviews: ['review-mcd-2'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-7',
    name: 'Tom Wilson',
    email: 'tom.wilson@example.com',
    avatar: null,
    reviews: ['review-mcd-3'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-8',
    name: 'Rachel Green',
    email: 'rachel.green@example.com',
    avatar: null,
    reviews: ['review-sb-1'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-9',
    name: 'Alex Chen',
    email: 'alex.chen@example.com',
    avatar: null,
    reviews: ['review-sb-2'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-10',
    name: 'Jessica Martinez',
    email: 'jessica.martinez@example.com',
    avatar: null,
    reviews: ['review-sephora-1'],
    is_deleted: false,
    is_restricted: false,
  },
  {
    id: 'user-11',
    name: 'Maria Rodriguez',
    email: 'maria.rodriguez@example.com',
    avatar: null,
    reviews: ['review-sephora-2'],
    is_deleted: false,
    is_restricted: false,
  },
];

