import { User } from '@/lib/types/user-types';

// Initial user data extracted from review-data.ts
// Compatible with User type from user-store.ts
export const initialUsersData: User[] = [
  {
    id: 'user-1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phoneNumber: '9999999999',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [
      {
        id: "addr-1",
        street: "548 Market Street",
        city: "San Francisco",
        state: "CA",
        zipCode: "94104",
        lat: 37.7897,
        lng: -122.4011,
        addressType: "house",
        gateCode: "111",
        deliveryPreference: "door",
        deliveryInstructions: "Please ring the bell and drop off at the door, thank you. Its around the corner on the ground floor"
      },
      {
        id: "addr-2",
        street: "47 West 13th Street",
        city: "New York",
        state: "NY",
        zipCode: "10011",
        lat: 40.7369,
        lng: -73.9968,
        addressType: "house"
      }
    ],
    is_restricted: false,
    reviews: [],
  },
  {
    id: 'user-2',
    name: 'Sarah Wilson',
    email: 'sarah.wilson@example.com',
    phoneNumber: '5550001002',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-philz-2', 'review-sarah-2', 'review-sarah-3'],
    is_restricted: false,
  },
  {
    id: 'user-3',
    name: 'Mike Johnson',
    email: 'mike.johnson@example.com',
    phoneNumber: '5550001003',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-philz-3'],
    is_restricted: true,
  },
  {
    id: 'user-4',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@example.com',
    phoneNumber: '5550001004',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-philz-4'],
    is_restricted: false,
  },
  {
    id: 'user-5',
    name: 'David Brown',
    email: 'david.brown@example.com',
    phoneNumber: '5550001005',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-mcd-1'],
    is_restricted: false,
  },
  {
    id: 'user-6',
    name: 'Emma Davis',
    email: 'emma.davis@example.com',
    phoneNumber: '5550001006',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-mcd-2'],
    is_restricted: false,
  },
  {
    id: 'user-7',
    name: 'Tom Wilson',
    email: 'tom.wilson@example.com',
    phoneNumber: '5550001007',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-mcd-3'],
    is_restricted: false,
  },
  {
    id: 'user-8',
    name: 'Rachel Green',
    email: 'rachel.green@example.com',
    phoneNumber: '5550001008',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-sb-1'],
    is_restricted: false,
  },
  {
    id: 'user-9',
    name: 'Alex Chen',
    email: 'alex.chen@example.com',
    phoneNumber: '5550001009',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-sb-2'],
    is_restricted: false,
  },
  {
    id: 'user-10',
    name: 'Jessica Martinez',
    email: 'jessica.martinez@example.com',
    phoneNumber: '5550001010',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-sephora-1'],
    is_restricted: false,
  },
  {
    id: 'user-11',
    name: 'Maria Rodriguez',
    email: 'maria.rodriguez@example.com',
    phoneNumber: '5550001011',
    password: 'password@12345',
    country: {
      dialCode: '+1',
      code: 'US',
      name: 'United States',
    },
    userCountry: 'United States',
    avatar: null,
    paymentMethods: [],
    addresses: [],
    reviews: ['review-sephora-2'],
    is_restricted: false,
  },
];

