'use client'

import { create } from "zustand"
import { persist } from "zustand/middleware"
import { MerchantStorageKeys } from "@/lib/utils/merchant-storage"

interface StoreSettings {
  storeName: string
  address: string
  phoneNumber: string
  website: string
  description: string
}

interface AccountSettings {
  autoGeneratedDescriptions: boolean
  alcoholSales: boolean
  useCustomerPhotos: boolean
  tabletAccess: boolean
  tabletPin: string
  chatFeature: boolean
  staffTips: boolean
}

interface SettingsStore {
  store: StoreSettings
  account: AccountSettings
  
  // Actions
  updateStoreSettings: (updates: Partial<StoreSettings>) => void
  updateAccountSettings: (updates: Partial<AccountSettings>) => void
}

const initialStoreSettings: StoreSettings = {
  storeName: "Frosty Bear test NCP 🐻🍯",
  address: "575 Bellevue Sq, Bellevue, WA 98004, USA",
  phoneNumber: "",
  website: "http://himalayan-grill.com",
  description: "start Hand crafted burgers, made the way they were intended to be. start Hand crafted burgers, made the way they were intended to be. start Hand crafted burgers, made the way they were intended to be."
}

const initialAccountSettings: AccountSettings = {
  autoGeneratedDescriptions: true,
  alcoholSales: false,
  useCustomerPhotos: false,
  tabletAccess: true,
  tabletPin: "1 2 3 6",
  chatFeature: true,
  staffTips: false
}

export const useMerchantSettingsStore = create<SettingsStore>()(
  persist(
    (set) => ({
      store: initialStoreSettings,
      account: initialAccountSettings,

      updateStoreSettings: (updates) =>
        set((state) => ({
          store: { ...state.store, ...updates }
        })),
      updateAccountSettings: (updates) =>
        set((state) => ({
          account: { ...state.account, ...updates }
        }))
    }),
    {
      name: MerchantStorageKeys.SETTINGS
    }
  )
)

