'use client';
import MerchantLayout from '@/components/merchant/MerchantLayout';
import { X, AlertCircle, Plus, Edit } from 'lucide-react';
import { Label } from '@/components/ui/label';
import { useMerchantPersistedState } from '@/lib/hooks/useMerchantPersistedState';
import { useMerchantSettingsStore } from '@/store/merchant-settings-store';

export default function AccountSettingsPage() {
  const { account, updateAccountSettings } = useMerchantSettingsStore();

  const [showAlert, setShowAlert] = useMerchantPersistedState(
    'settings',
    'account',
    'showAlert',
    true
  );
  const [autoGeneratedDescriptions, setAutoGeneratedDescriptions] = useMerchantPersistedState(
    'settings',
    'account',
    'autoGeneratedDescriptions',
    account.autoGeneratedDescriptions
  );
  const [tabletAccess, setTabletAccess] = useMerchantPersistedState(
    'settings',
    'account',
    'tabletAccess',
    account.tabletAccess
  );
  const [chatFeature, setChatFeature] = useMerchantPersistedState(
    'settings',
    'account',
    'chatFeature',
    account.chatFeature
  );
  const [staffTips, setStaffTips] = useMerchantPersistedState(
    'settings',
    'account',
    'staffTips',
    account.staffTips
  );
  const [pin, setPin] = useMerchantPersistedState('settings', 'account', 'pin', account.tabletPin);

  return (
    <MerchantLayout>
      <div className="max-w-4xl">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Account settings</h1>
        </div>

        {/* Alert Banner */}
        {showAlert && (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6 flex items-start gap-3 relative">
            <AlertCircle className="h-5 w-5 text-yellow-600 mt-0.5 flex-shrink-0" />
            <p className="text-sm text-gray-800 flex-1">
              You do not have permission to access the daily payout currently.
            </p>
            <button
              onClick={() => setShowAlert(false)}
              className="absolute top-4 right-4 text-gray-400 hover:text-gray-600"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        )}

        {/* Menu Settings */}
        <div className="bg-white border border-gray-200 rounded-lg p-6 mb-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Menu Settings</h2>

          {/* Use auto-generated menu descriptions */}
          <div className="flex items-start justify-between py-4 border-b border-gray-200">
            <div className="flex-1">
              <h3 className="text-base font-medium text-gray-900 mb-1">
                Use auto-generated menu descriptions
              </h3>
              <p className="text-sm text-gray-600 mb-2">
                Add AI-powered descriptions to items that don't already have them across all of your
                stores.
              </p>
              {/* <a href="#" className="text-sm text-blue-600 hover:underline">
                Learn more
              </a> */}
            </div>
            <label className="relative inline-flex items-center cursor-pointer ml-4">
              <input
                type="checkbox"
                checked={autoGeneratedDescriptions}
                onChange={e => {
                  setAutoGeneratedDescriptions(e.target.checked);
                  updateAccountSettings({ autoGeneratedDescriptions: e.target.checked });
                }}
                className="sr-only peer"
              />
              <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-red-500 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-gray-900"></div>
            </label>
          </div>

          {/* Alcohol sales */}
          <div className="flex items-start justify-between py-4 border-b border-gray-200">
            <div className="flex-1">
              <h3 className="text-base font-medium text-gray-900 mb-1">Alcohol sales</h3>
              <p className="text-sm text-gray-600 mb-2">
                Sell alcohol on DashDoor in compliance with local laws and regulations. To get
                started, confirm that alcohol delivery is allowed in your state.
              </p>
              {/* <a href="#" className="text-sm text-blue-600 hover:underline">
                Learn more
              </a> */}
            </div>
            {/* <button className="ml-4 px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md transition-colors">
              Add
            </button> */}
          </div>

          {/* Use item photos from customers */}
          <div className="flex items-start justify-between py-4">
            <div className="flex-1">
              <h3 className="text-base font-medium text-gray-900 mb-1">
                Use item photos from customers
              </h3>
              <p className="text-sm text-gray-600 mb-2">
                DashDoor only adds photos to your menu when there&apos;re items missing photos. All
                photos from customers will be permanently removed if you turn it off.
              </p>
              <span className="inline-block px-2 py-0.5 bg-yellow-100 text-yellow-800 text-xs font-medium rounded">
                DashDoor employees only
              </span>
            </div>
            <div className="ml-4 text-sm text-gray-600">Turned off</div>
          </div>
        </div>

        {/* Tablet Settings */}
        <div className="bg-white border border-gray-200 rounded-lg p-6 mb-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Tablet Settings</h2>

          {/* Tablet access */}
          <div className="flex items-start justify-between py-4 border-b border-gray-200">
            <div className="flex-1">
              <h3 className="text-base font-medium text-gray-900 mb-1">Tablet access</h3>
              <p className="text-sm text-gray-600 mb-3">
                Create and manage your PIN to pause your store on the DashDoor Tablet.
              </p>
              <div className="flex items-center gap-3">
                <div className="flex items-center gap-2">
                  {pin.split(' ').map((digit, index) => (
                    <span key={index} className="text-lg font-semibold text-gray-900">
                      {digit}
                    </span>
                  ))}
                </div>
                {/* <button className="text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1">
                  <Edit className="h-3 w-3" />
                  Edit
                </button> */}
              </div>
            </div>
            <label className="relative inline-flex items-center cursor-pointer ml-4">
              <input
                type="checkbox"
                checked={tabletAccess}
                onChange={e => {
                  setTabletAccess(e.target.checked);
                  updateAccountSettings({ tabletAccess: e.target.checked });
                }}
                className="sr-only peer"
              />
              <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-red-500 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-gray-900"></div>
            </label>
          </div>

          {/* Chat feature */}
          <div className="flex items-start justify-between py-4">
            <div className="flex-1">
              <h3 className="text-base font-medium text-gray-900 mb-1">Chat feature</h3>
              <p className="text-sm text-gray-600">
                Add chat functionality to contact customers directly through the DashDoor Tablet.
              </p>
            </div>
            <label className="relative inline-flex items-center cursor-pointer ml-4">
              <input
                type="checkbox"
                checked={chatFeature}
                onChange={e => {
                  setChatFeature(e.target.checked);
                  updateAccountSettings({ chatFeature: e.target.checked });
                }}
                className="sr-only peer"
              />
              <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-red-500 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-gray-900"></div>
            </label>
          </div>
        </div>

        {/* Dasher pickup instructions */}
        <div className="bg-white border border-gray-200 rounded-lg p-6 mb-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Dasher pickup instructions</h2>
          <p className="text-sm text-gray-600 mb-6">
            Provide Dashers with instructions to help them navigate your store and improve the order
            delivery experience.
          </p>

          {/* Default instructions */}
          <div className="mb-6 pb-6 border-b border-gray-200">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-base font-medium text-gray-900">Default instructions</h3>
              {/* <button className="text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1">
                <Edit className="h-3 w-3" />
                Edit
              </button> */}
            </div>
            <p className="text-sm text-gray-600 mb-2">
              Dashers will use these instructions when picking up orders from your store.
            </p>
            <div className="space-y-3 mt-4">
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-1 block">
                  Instructions for parking at your store:
                </Label>
                <p className="text-sm text-gray-900">
                  You can park in the Street parking by the Street.
                </p>
              </div>
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-1 block">
                  Instructions for picking up food at your store:
                </Label>
                <p className="text-sm text-gray-900">
                  Enter through the Front door and pick up the order from the Host stand.
                </p>
              </div>
              <div>
                <Label className="text-sm font-medium text-gray-700 mb-1 block">
                  Additional notes:
                </Label>
                <p className="text-sm text-gray-900">
                  PLEASE NOTE: You need to take the elevator to the 5th floor and once you are in
                  the floor, go to the left and the restaurant is going to be like 5 mts Necesitas
                  tomar el elevador al piso 5 y una vez ahi, a la izquierda esta el restaurante como
                  a 5 mt
                </p>
              </div>
            </div>
          </div>

          {/* Dynamic instructions */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <h3 className="text-base font-medium text-gray-900">Dynamic instructions</h3>
              {/* <button className="inline-flex items-center gap-2 px-4 py-2 bg-red-600 hover:bg-red-700 text-white text-sm font-medium rounded-md transition-colors">
                <Plus className="h-4 w-4" />
                Add
              </button> */}
            </div>
            <p className="text-sm text-gray-600">
              Create pickup instructions for Dashers who will arrive at specific times of the day or
              certain days of the week. This is great for Merchants who offer multiple ways for
              Dashers to pick up orders. Default pickup instructions are required to add this
              option.
            </p>
          </div>
        </div>

        {/* Customer pickup instructions */}
        <div className="bg-white border border-gray-200 rounded-lg p-6 mb-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Customer pickup instructions</h2>
          <div className="flex items-center justify-between">
            <p className="text-sm text-gray-600">
              You haven't provided any customer pickup instructions. Adding them can help customers
              pick up orders faster.
            </p>
            {/* <button className="text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1">
              <Edit className="h-3 w-3" />
              Edit
            </button> */}
          </div>
        </div>

        {/* Staff tips for pickup orders */}
        <div className="bg-white border border-gray-200 rounded-lg p-6">
          <div className="flex items-start justify-between">
            <div className="flex-1">
              <h3 className="text-base font-medium text-gray-900 mb-1">
                Staff tips for pickup orders
              </h3>
              <p className="text-sm text-gray-600 mb-2">
                100% of accepted tips must be distributed to your staff.
              </p>
              {/* <a href="#" className="text-sm text-blue-600 hover:underline">
                Learn more
              </a> */}
            </div>
            <label className="relative inline-flex items-center cursor-pointer ml-4">
              <input
                type="checkbox"
                checked={staffTips}
                onChange={e => {
                  setStaffTips(e.target.checked);
                  updateAccountSettings({ staffTips: e.target.checked });
                }}
                className="sr-only peer"
              />
              <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-2 peer-focus:ring-red-500 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-gray-900"></div>
            </label>
          </div>
        </div>
      </div>
    </MerchantLayout>
  );
}
