-- Persona catalog moves — GENERATED by scripts/move-restaurants-near-personas.ts.
-- Source of truth: data/reco-personas/personas.json. Do not hand-edit.
-- Idempotent — each move is a plain UPDATE keyed by restaurant id.

PRAGMA foreign_keys = ON;
BEGIN;

-- alice-tran (user 3101) — 3 moves
UPDATE restaurants SET latitude = 40.547028, longitude = -74.094149 WHERE id = 1; -- Thai for alice-tran
UPDATE restaurants SET latitude = 40.547028, longitude = -74.094149 WHERE id = 454; -- Vietnamese for alice-tran
UPDATE restaurants SET latitude = 40.547028, longitude = -74.094149 WHERE id = 523; -- Japanese for alice-tran

-- ben-kowalski (user 3102) — 5 moves
UPDATE restaurants SET latitude = 33.863187, longitude = -118.434225 WHERE id = 478; -- Mediterranean for ben-kowalski
UPDATE restaurants SET latitude = 33.90823, longitude = -118.474625 WHERE id = 508; -- Mediterranean for ben-kowalski
UPDATE restaurants SET latitude = 33.971062, longitude = -118.399955 WHERE id = 403; -- Mediterranean for ben-kowalski
UPDATE restaurants SET latitude = 33.908698, longitude = -118.274437 WHERE id = 80; -- Mediterranean for ben-kowalski
UPDATE restaurants SET latitude = 33.759329, longitude = -118.323858 WHERE id = 226; -- Mediterranean for ben-kowalski

-- chloe-okafor (user 3103) — 10 moves
UPDATE restaurants SET latitude = 34.04504, longitude = -118.296337 WHERE id = 468; -- Indian for chloe-okafor
UPDATE restaurants SET latitude = 34.126136, longitude = -118.324534 WHERE id = 552; -- Indian for chloe-okafor
UPDATE restaurants SET latitude = 34.150866, longitude = -118.177109 WHERE id = 383; -- Indian for chloe-okafor
UPDATE restaurants SET latitude = 34.04504, longitude = -118.296337 WHERE id = 167; -- Mediterranean for chloe-okafor
UPDATE restaurants SET latitude = 34.126136, longitude = -118.324534 WHERE id = 195; -- Mediterranean for chloe-okafor
UPDATE restaurants SET latitude = 34.04504, longitude = -118.296337 WHERE id = 522; -- Mexican for chloe-okafor
UPDATE restaurants SET latitude = 34.107357, longitude = -118.33981 WHERE id = 465; -- Mexican for chloe-okafor
UPDATE restaurants SET latitude = 34.177355, longitude = -118.245676 WHERE id = 491; -- Mexican for chloe-okafor
UPDATE restaurants SET latitude = 34.101558, longitude = -118.106183 WHERE id = 225; -- Mexican for chloe-okafor
UPDATE restaurants SET latitude = 33.937523, longitude = -118.167569 WHERE id = 307; -- Mexican for chloe-okafor

-- diego-mendoza (user 3104) — 3 moves
UPDATE restaurants SET latitude = 34.000146, longitude = -118.323708 WHERE id = 369; -- American for diego-mendoza
UPDATE restaurants SET latitude = 34.1021, longitude = -118.350639 WHERE id = 161; -- American for diego-mendoza
UPDATE restaurants SET latitude = 34.12505, longitude = -118.17804 WHERE id = 34; -- American for diego-mendoza

-- eli-nakamura (user 3105) — 2 moves
UPDATE restaurants SET latitude = 40.666111, longitude = -74.02806 WHERE id = 94; -- Korean for eli-nakamura
UPDATE restaurants SET latitude = 40.788899, longitude = -74.055219 WHERE id = 420; -- Korean for eli-nakamura

-- gabe-jensen (user 3107) — 15 moves
UPDATE restaurants SET latitude = 42.281362, longitude = -71.174448 WHERE id = 178; -- American for gabe-jensen
UPDATE restaurants SET latitude = 42.413547, longitude = -71.228609 WHERE id = 345; -- American for gabe-jensen
UPDATE restaurants SET latitude = 42.506771, longitude = -71.033093 WHERE id = 73; -- American for gabe-jensen
UPDATE restaurants SET latitude = 42.354021, longitude = -71.035423 WHERE id = 350; -- American for gabe-jensen
UPDATE restaurants SET latitude = 42.298027, longitude = -71.041222 WHERE id = 187; -- American for gabe-jensen
UPDATE restaurants SET latitude = 42.281362, longitude = -71.174448 WHERE id = 143; -- Italian for gabe-jensen
UPDATE restaurants SET latitude = 42.413547, longitude = -71.228609 WHERE id = 268; -- Italian for gabe-jensen
UPDATE restaurants SET latitude = 42.506771, longitude = -71.033093 WHERE id = 261; -- Italian for gabe-jensen
UPDATE restaurants SET latitude = 42.354021, longitude = -71.035423 WHERE id = 272; -- Italian for gabe-jensen
UPDATE restaurants SET latitude = 42.298027, longitude = -71.041222 WHERE id = 301; -- Italian for gabe-jensen
UPDATE restaurants SET latitude = 42.281362, longitude = -71.174448 WHERE id = 330; -- Mexican for gabe-jensen
UPDATE restaurants SET latitude = 42.413547, longitude = -71.228609 WHERE id = 103; -- Mexican for gabe-jensen
UPDATE restaurants SET latitude = 42.506771, longitude = -71.033093 WHERE id = 346; -- Mexican for gabe-jensen
UPDATE restaurants SET latitude = 42.354021, longitude = -71.035423 WHERE id = 258; -- Mexican for gabe-jensen
UPDATE restaurants SET latitude = 42.298027, longitude = -71.041222 WHERE id = 171; -- Mexican for gabe-jensen

-- hana-park (user 3108) — 7 moves
UPDATE restaurants SET latitude = 33.984982, longitude = -118.40447 WHERE id = 511; -- Korean for hana-park
UPDATE restaurants SET latitude = 34.17, longitude = -118.417749 WHERE id = 78; -- Korean for hana-park
UPDATE restaurants SET latitude = 34.178614, longitude = -118.144689 WHERE id = 339; -- Korean for hana-park
UPDATE restaurants SET latitude = 34.030228, longitude = -118.265643 WHERE id = 288; -- Korean for hana-park
UPDATE restaurants SET latitude = 33.984982, longitude = -118.40447 WHERE id = 439; -- Chinese for hana-park
UPDATE restaurants SET latitude = 34.17, longitude = -118.417749 WHERE id = 512; -- Chinese for hana-park
UPDATE restaurants SET latitude = 34.178614, longitude = -118.144689 WHERE id = 475; -- Chinese for hana-park

-- idris-mensah (user 3109) — 2 moves
UPDATE restaurants SET latitude = 40.578871, longitude = -74.042234 WHERE id = 456; -- Italian for idris-mensah
UPDATE restaurants SET latitude = 40.78447, longitude = -74.050743 WHERE id = 89; -- Italian for idris-mensah

-- julia-volkov (user 3110) — 5 moves
UPDATE restaurants SET latitude = 40.602577, longitude = -74.139827 WHERE id = 437; -- Vietnamese for julia-volkov
UPDATE restaurants SET latitude = 40.82865, longitude = -74.141337 WHERE id = 405; -- Vietnamese for julia-volkov
UPDATE restaurants SET latitude = 40.723601, longitude = -73.949912 WHERE id = 536; -- Vietnamese for julia-volkov
UPDATE restaurants SET latitude = 40.602577, longitude = -74.139827 WHERE id = 544; -- Thai for julia-volkov
UPDATE restaurants SET latitude = 40.82865, longitude = -74.141337 WHERE id = 415; -- Thai for julia-volkov

COMMIT;
