/**
 * Generates data/db/schema/personas_seed.sql from data/reco-personas/personas.json.
 *
 * Reads the persona JSON, queries dashdoor.db for matching restaurants + menu items,
 * and writes idempotent INSERT statements covering:
 *   - users, addresses
 *   - user_preferences, user_family
 *   - orders, order_items (8–20 per persona, proportional to cuisine_affinity)
 *   - user_reviews (≥2 with rating ≤ 2 per persona)
 *
 * Run: npx tsx scripts/gen-personas-seed.ts
 */

// @ts-expect-error — better-sqlite3 ships without types; this is a one-shot generator.
import Database from 'better-sqlite3';
import { readFileSync, writeFileSync } from 'fs';

const ROOT = process.cwd();
const DB_PATH = `${ROOT}/data/db/dashdoor.db`;
const PERSONAS_PATH = `${ROOT}/data/reco-personas/personas.json`;
const OUT_PATH = `${ROOT}/data/db/schema/personas_seed.sql`;

type Persona = {
  id: string;
  user_id: number;
  display_name: string;
  email: string;
  address: {
    line1: string;
    city: string;
    state: string;
    zip: string;
    lat: number;
    lng: number;
  };
  story: string;
  preferences: {
    cuisine_affinity: Record<string, number>;
    price_tier: 'budget' | 'mid' | 'premium';
    dietary: string[];
    spice_tolerance: 'mild' | 'medium' | 'hot';
    novelty_appetite: number;
    delivery_time_tolerance: 'quick' | 'flexible';
    promo_sensitivity: 'low' | 'mid' | 'high';
  };
  family: null | {
    adults: number;
    kids: number;
    kid_ages: number[];
    shared_dietary: string[];
    kid_friendly_required: boolean;
    notes?: string;
  };
};

// Deterministic RNG (LCG) so re-runs produce byte-identical SQL.
function makeRng(seed: number) {
  let state = seed >>> 0;
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 0x100000000;
  };
}
const pick = <T>(rng: () => number, arr: T[]) => arr[Math.floor(rng() * arr.length)];
const pickN = <T>(rng: () => number, arr: T[], n: number): T[] => {
  const copy = [...arr];
  const out: T[] = [];
  for (let i = 0; i < n && copy.length > 0; i++) {
    const idx = Math.floor(rng() * copy.length);
    out.push(copy[idx]);
    copy.splice(idx, 1);
  }
  return out;
};
const sq = (s: string) => "'" + s.replace(/'/g, "''") + "'";

function priceRangesFor(tier: 'budget' | 'mid' | 'premium'): number[] {
  if (tier === 'budget') return [1];
  if (tier === 'mid') return [2];
  return [3, 4];
}

const db = new Database(DB_PATH, { readonly: true });
const personas: Persona[] = JSON.parse(readFileSync(PERSONAS_PATH, 'utf8'));

// Seed restaurants must be nearby — same radius the rule uses.
// Keeps the persona's order history coherent with their address.
const SEED_RADIUS_MILES = 25;

function haversineMiles(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 3958.8;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

const restaurantsStmt = db.prepare(`
  SELECT id, name, latitude, longitude FROM restaurants
  WHERE cuisine = ? AND price_range IN (SELECT value FROM json_each(?))
`);
const restaurantsBroadStmt = db.prepare(`
  SELECT id, name, latitude, longitude FROM restaurants WHERE cuisine = ?
`);
const menuItemsStmt = db.prepare(`
  SELECT id, price FROM menu_items WHERE restaurant_id = ? AND (is_available IS NULL OR is_available = 1) LIMIT 20
`);

const out: string[] = [];
out.push('-- Personas seed — GENERATED by scripts/gen-personas-seed.ts');
out.push('-- Source of truth: data/reco-personas/personas.json. Do not hand-edit.');
out.push('-- Idempotent: wipes the persona slice (users 3101–3110) and rewrites it.');
out.push('');
out.push('PRAGMA foreign_keys = ON;');
out.push('BEGIN;');
out.push('');
out.push('-- 1. Wipe the persona slice (children-first so FKs stay happy).');
out.push('DELETE FROM user_reviews    WHERE user_id BETWEEN 3101 AND 3110;');
out.push('DELETE FROM order_items     WHERE order_id IN (SELECT id FROM orders WHERE user_id BETWEEN 3101 AND 3110);');
out.push('DELETE FROM orders          WHERE user_id BETWEEN 3101 AND 3110;');
out.push('DELETE FROM user_family     WHERE user_id BETWEEN 3101 AND 3110;');
out.push('DELETE FROM user_preferences WHERE user_id BETWEEN 3101 AND 3110;');
out.push('DELETE FROM addresses       WHERE user_id BETWEEN 3101 AND 3110;');
out.push('');

// Counters for the ID ranges we reserve for personas.
let nextOrderId = 9_000_001;
let nextOrderItemId = 9_000_001;
let nextReviewId = 9_000_001;

let totalOrders = 0;
let totalReviews = 0;

for (const p of personas) {
  const rng = makeRng(p.user_id);
  out.push('-- =====================================================');
  out.push(`-- ${p.id} (user ${p.user_id}) — ${p.story}`);
  out.push('-- =====================================================');

  // 2. users — INSERT OR REPLACE so changes to display_name/email propagate.
  const phone = `555${String(p.user_id).padStart(7, '0')}`;
  out.push(
    `INSERT OR REPLACE INTO users (id, name, email, phone_number, password, country_id, avatar, is_restricted) VALUES ` +
      `(${p.user_id}, ${sq(p.display_name)}, ${sq(p.email)}, '${phone}', 'password', 2, NULL, 0);`
  );

  // 3. addresses — one per persona, ids 9001..9010.
  const addrId = 9000 + (p.user_id - 3100);
  out.push(
    `INSERT INTO addresses (id, user_id, street, city, state, zip_code, latitude, longitude, address_type, is_default) VALUES ` +
      `(${addrId}, ${p.user_id}, ${sq(p.address.line1)}, ${sq(p.address.city)}, ${sq(p.address.state)}, ${sq(p.address.zip)}, ${p.address.lat}, ${p.address.lng}, 'house', 1);`
  );

  // 4. user_preferences
  const pr = p.preferences;
  out.push(
    `INSERT INTO user_preferences (user_id, cuisine_affinity, price_tier, dietary, spice_tolerance, novelty_appetite, delivery_time_tolerance, promo_sensitivity) VALUES ` +
      `(${p.user_id}, ${sq(JSON.stringify(pr.cuisine_affinity))}, ${sq(pr.price_tier)}, ${sq(JSON.stringify(pr.dietary))}, ${sq(pr.spice_tolerance)}, ${pr.novelty_appetite}, ${sq(pr.delivery_time_tolerance)}, ${sq(pr.promo_sensitivity)});`
  );

  // 5. user_family
  if (p.family) {
    const f = p.family;
    out.push(
      `INSERT INTO user_family (user_id, adults, kids, kid_ages, shared_dietary, kid_friendly_required, notes) VALUES ` +
        `(${p.user_id}, ${f.adults}, ${f.kids}, ${sq(JSON.stringify(f.kid_ages))}, ${sq(JSON.stringify(f.shared_dietary))}, ${f.kid_friendly_required ? 1 : 0}, ${f.notes ? sq(f.notes) : 'NULL'});`
    );
  }

  // 6. orders + order_items. Number of orders scales with whether they have a family.
  const isFamily = p.family !== null;
  const totalOrdersForPersona = isFamily ? 12 + Math.floor(rng() * 7) : 8 + Math.floor(rng() * 6); // 12-18 vs 8-13
  const priceRanges = priceRangesFor(pr.price_tier);
  const priceRangesJson = JSON.stringify(priceRanges);

  // Distribute orders across cuisines proportional to affinity weights.
  const cuisines = Object.entries(pr.cuisine_affinity);
  const totalWeight = cuisines.reduce((s, [, w]) => s + w, 0);
  const cuisineOrderCounts: Array<{ cuisine: string; weight: number; orders: number }> = [];
  let remaining = totalOrdersForPersona;
  cuisines.forEach(([cuisine, weight], i) => {
    const isLast = i === cuisines.length - 1;
    const n = isLast ? remaining : Math.max(1, Math.round((weight / totalWeight) * totalOrdersForPersona));
    cuisineOrderCounts.push({ cuisine, weight, orders: n });
    remaining -= n;
  });

  // Pick restaurants for this persona. Each cuisine gets 1-3 restaurants,
  // all within SEED_RADIUS_MILES of the persona's address.
  const personaRestaurants: Array<{ id: number; name: string; cuisine: string; weight: number; orderCount: number }> = [];
  const withinRadius = (rs: Array<{ id: number; name: string; latitude: number | null; longitude: number | null }>) =>
    rs.filter(
      (r) =>
        r.latitude != null &&
        r.longitude != null &&
        haversineMiles(p.address.lat, p.address.lng, r.latitude, r.longitude) <= SEED_RADIUS_MILES,
    );
  for (const { cuisine, weight, orders } of cuisineOrderCounts) {
    const tierMatches = restaurantsStmt.all(cuisine, priceRangesJson) as Array<{
      id: number;
      name: string;
      latitude: number | null;
      longitude: number | null;
    }>;
    let rests: Array<{ id: number; name: string }> = withinRadius(tierMatches);
    if (rests.length === 0) {
      // Fallback: broaden to any price tier, but stay in radius.
      const broad = restaurantsBroadStmt.all(cuisine) as Array<{
        id: number;
        name: string;
        latitude: number | null;
        longitude: number | null;
      }>;
      rests = withinRadius(broad);
    }
    if (rests.length === 0) continue;
    const n = Math.min(rests.length, Math.max(1, Math.ceil(orders / 2)));
    const chosen = pickN(rng, rests, n);
    // Spread `orders` across the chosen restaurants — favor the first.
    chosen.forEach((r, idx) => {
      const share = Math.max(1, Math.round(orders * (n - idx) / ((n * (n + 1)) / 2)));
      personaRestaurants.push({ id: r.id, name: r.name, cuisine, weight, orderCount: share });
    });
  }

  // Day offsets — most recent first, spread across last 120 days.
  const today = new Date('2026-05-28T18:00:00');
  let dayOffset = 1;

  for (const r of personaRestaurants) {
    const items = menuItemsStmt.all(r.id) as Array<{ id: number; price: number }>;
    if (items.length === 0) continue;

    for (let o = 0; o < r.orderCount; o++) {
      const orderId = nextOrderId++;
      const itemCount = isFamily ? 2 + Math.floor(rng() * 3) : 1 + Math.floor(rng() * 2); // 2-4 vs 1-2
      const picked = pickN(rng, items, Math.min(itemCount, items.length));
      let subtotal = 0;
      const orderItemRows: string[] = [];
      for (const it of picked) {
        const qty = isFamily && rng() > 0.5 ? 2 : 1;
        subtotal += it.price * qty;
        orderItemRows.push(`(${nextOrderItemId++}, ${orderId}, ${it.id}, ${qty})`);
      }
      const serviceFee = Math.max(199, Math.round(subtotal * 0.12));
      const deliveryFee = 399;
      const tip = Math.round(subtotal * 0.1);
      const total = subtotal + serviceFee + deliveryFee + tip;
      const date = new Date(today.getTime() - dayOffset * 86400_000);
      dayOffset += 1 + Math.floor(rng() * 3); // 1-3 days between orders
      const orderDate = date.toISOString();

      out.push(
        `INSERT INTO orders (id, user_id, store_id, store_category, payment_method_id, address_id, delivery_type, delivery_time_str, extra_fee, phone_country_code, phone_number, tip_amount, subtotal, service_fee, delivery_fee, total, order_date, status) VALUES ` +
          `(${orderId}, ${p.user_id}, ${r.id}, 'restaurant', NULL, ${addrId}, 'delivery', '25-40 min', 0, '+1', '${phone}', ${tip}, ${subtotal}, ${serviceFee}, ${deliveryFee}, ${total}, ${sq(orderDate)}, 'delivered');`
      );
      out.push(`INSERT INTO order_items (id, order_id, menu_item_id, quantity) VALUES ${orderItemRows.join(', ')};`);
      totalOrders++;
    }
  }

  // 7. user_reviews — 5–12 total, ≥2 negative (rating ≤ 2).
  //
  // Negative-review heuristic: pick restaurants the persona ordered from
  // *least* often (so the rule's job is "block this place even though the
  // persona's history touches it"). Positive reviews go on the most-ordered
  // restaurants (the rule's "familiar" picks).
  if (personaRestaurants.length > 0) {
    const sortedByCount = [...personaRestaurants].sort((a, b) => a.orderCount - b.orderCount);
    const negativeTargets = sortedByCount.slice(0, 2); // 2 least-ordered
    const positivePool = personaRestaurants.filter((r) => !negativeTargets.find((n) => n.id === r.id));
    const reviewCount = Math.min(personaRestaurants.length, 5 + Math.floor(rng() * 5)); // 5–9
    const positiveCount = Math.max(0, reviewCount - negativeTargets.length);

    const reviews: Array<{ restId: number; rating: number; content: string }> = [];
    negativeTargets.forEach((r, i) => {
      const rating = 1.0 + Math.floor(rng() * 2); // 1 or 2
      reviews.push({
        restId: r.id,
        rating,
        content:
          rating <= 1
            ? `Tried ${r.name} once, didn't land. Won't reorder.`
            : `${r.name} was underwhelming — kitchen seemed off the night I ordered.`,
      });
    });
    pickN(rng, positivePool, positiveCount).forEach((r) => {
      const rating = 4.0 + Math.floor(rng() * 2); // 4 or 5
      reviews.push({
        restId: r.id,
        rating,
        content:
          rating >= 5
            ? `${r.name} nails it every time — go-to for ${r.cuisine}.`
            : `Solid ${r.cuisine} from ${r.name}. Consistently good.`,
      });
    });

    let revOffset = 5;
    for (const rev of reviews) {
      const reviewId = nextReviewId++;
      const ts = new Date(today.getTime() - revOffset * 86400_000).toISOString();
      revOffset += 2 + Math.floor(rng() * 5);
      out.push(
        `INSERT INTO user_reviews (id, store_id, store_category, user_id, rating, content, timestamp, order_id, approval_status) VALUES ` +
          `(${reviewId}, ${rev.restId}, 'restaurant', ${p.user_id}, ${rev.rating.toFixed(1)}, ${sq(rev.content)}, ${sq(ts)}, NULL, 'approved');`
      );
      totalReviews++;
    }
  }

  out.push('');
}

out.push('COMMIT;');
out.push('');

writeFileSync(OUT_PATH, out.join('\n'));

console.log(`Wrote ${OUT_PATH}`);
console.log(`  ${personas.length} personas, ${totalOrders} orders, ${totalReviews} reviews`);
