/**
 * Pulls catalog restaurants closer to each persona so the rule has enough
 * cuisine+tier options within the 15-mile candidate radius.
 *
 * Reads data/reco-personas/personas.json, queries data/db/dashdoor.db, and
 * for each (persona × cuisine in cuisine_affinity × persona price_tier),
 * ensures at least TARGET_PER_COMBO restaurants exist within
 * CANDIDATE_RADIUS_MILES. If short, picks the closest matching restaurants
 * that sit *outside* the radius and shifts their lat/lng to a deterministic
 * point inside the persona's radius.
 *
 * Writes data/db/schema/personas_catalog_moves.sql with idempotent UPDATE
 * statements (you can re-run the script and re-apply at any time).
 *
 * Run: npx tsx scripts/move-restaurants-near-personas.ts
 */

// @ts-expect-error — better-sqlite3 ships without types.
import Database from 'better-sqlite3';
import { readFileSync, writeFileSync } from 'fs';

import type { Persona, PriceTier } from '../lib/reco/types';

const ROOT = process.cwd();
const DB_PATH = `${ROOT}/data/db/dashdoor.db`;
const PERSONAS_PATH = `${ROOT}/data/reco-personas/personas.json`;
const OUT_PATH = `${ROOT}/data/db/schema/personas_catalog_moves.sql`;

const TARGET_PER_COMBO = 6;       // 3 familiar + 1 new + 2 buffer
const RULE_RADIUS_MILES = 15;
const PLACE_INNER_MILES_MIN = 2;  // don't pile them all on top of the persona
const PLACE_INNER_MILES_MAX = 12;

const PRICE_RANGES: Record<PriceTier, number[]> = {
  budget: [1],
  mid: [2],
  premium: [3, 4],
};

function haversineMiles(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 3958.8;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}

/** Offset (lat, lng) by `miles` along the given bearing (degrees). */
function offsetLatLng(lat: number, lng: number, miles: number, bearingDeg: number): [number, number] {
  const R = 3958.8;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const toDeg = (r: number) => (r * 180) / Math.PI;
  const brng = toRad(bearingDeg);
  const lat1 = toRad(lat);
  const lng1 = toRad(lng);
  const d = miles / R;
  const lat2 = Math.asin(Math.sin(lat1) * Math.cos(d) + Math.cos(lat1) * Math.sin(d) * Math.cos(brng));
  const lng2 =
    lng1 + Math.atan2(Math.sin(brng) * Math.sin(d) * Math.cos(lat1), Math.cos(d) - Math.sin(lat1) * Math.sin(lat2));
  return [+toDeg(lat2).toFixed(6), +toDeg(lng2).toFixed(6)];
}

const personas: Persona[] = JSON.parse(readFileSync(PERSONAS_PATH, 'utf8'));
const db = new Database(DB_PATH, { readonly: true });

type RestRow = { id: number; cuisine: string; price_range: number; latitude: number; longitude: number };

const sql: string[] = [];
sql.push('-- Persona catalog moves — GENERATED by scripts/move-restaurants-near-personas.ts.');
sql.push('-- Source of truth: data/reco-personas/personas.json. Do not hand-edit.');
sql.push('-- Idempotent — each move is a plain UPDATE keyed by restaurant id.');
sql.push('');
sql.push('PRAGMA foreign_keys = ON;');
sql.push('BEGIN;');
sql.push('');

const movedIds = new Set<number>();   // a restaurant only moves once across all combos
let totalMoves = 0;

for (const p of personas) {
  const personaMoves: string[] = [];
  const tiers = PRICE_RANGES[p.preferences.price_tier];
  for (const cuisine of Object.keys(p.preferences.cuisine_affinity)) {
    // All restaurants of this cuisine in the persona's tier.
    const rows = db
      .prepare(
        `SELECT id, cuisine, price_range, latitude, longitude FROM restaurants
         WHERE cuisine = ? AND price_range IN (${tiers.join(',')}) AND latitude IS NOT NULL`,
      )
      .all(cuisine) as RestRow[];

    const withDist = rows.map((r) => ({
      ...r,
      dist: haversineMiles(p.address.lat, p.address.lng, r.latitude, r.longitude),
    }));
    const nearby = withDist.filter((r) => r.dist <= RULE_RADIUS_MILES);
    if (nearby.length >= TARGET_PER_COMBO) continue;

    const deficit = TARGET_PER_COMBO - nearby.length;
    // Take the closest restaurants currently OUTSIDE the radius, skipping any
    // we've already moved for another (persona, cuisine) combo.
    const candidates = withDist
      .filter((r) => r.dist > RULE_RADIUS_MILES && !movedIds.has(r.id))
      .sort((a, b) => a.dist - b.dist)
      .slice(0, deficit);

    candidates.forEach((r, i) => {
      const bearing = (360 / Math.max(deficit, 4)) * i + p.user_id; // de-overlap across personas
      const miles =
        PLACE_INNER_MILES_MIN +
        ((i * 2 + p.user_id) % (PLACE_INNER_MILES_MAX - PLACE_INNER_MILES_MIN + 1));
      const [newLat, newLng] = offsetLatLng(p.address.lat, p.address.lng, miles, bearing);
      personaMoves.push(
        `UPDATE restaurants SET latitude = ${newLat}, longitude = ${newLng} WHERE id = ${r.id}; -- ${cuisine} for ${p.id}`,
      );
      movedIds.add(r.id);
      totalMoves++;
    });
  }

  if (personaMoves.length > 0) {
    sql.push(`-- ${p.id} (user ${p.user_id}) — ${personaMoves.length} moves`);
    sql.push(...personaMoves);
    sql.push('');
  }
}

sql.push('COMMIT;');
sql.push('');

writeFileSync(OUT_PATH, sql.join('\n'));
console.log(`Wrote ${OUT_PATH}`);
console.log(`  ${totalMoves} restaurants moved across ${personas.length} personas`);
